<?php
// auth-generated by FilterConfigHandler
// date: 05/05/2015 07:29:38

$filters = array();
$filter = new \Mojavi\Filter\ExecutionTimeFilter();
$filter->initialize($this->context, array('comment' => true));
$filters[] = $filter;
$list[$moduleName] =& $filters;
?>