<?php
// auth-generated by RootConfigHandler
// date: 05/05/2015 07:29:38

self::$handlers['config/autoload.ini'] = new \Mojavi\Config\AutoloadConfigHandler();
self::$handlers['config/databases.ini'] = new \Mojavi\Config\DatabaseConfigHandler();
self::$handlers['config/settings.ini'] = new \Mojavi\Config\DefineConfigHandler();
self::$handlers['config/settings.ini']->initialize(array('prefix' => 'MO_'));
self::$handlers['factories.ini'] = new \Mojavi\Config\FactoryConfigHandler();
self::$handlers['filters.ini'] = new \Mojavi\Config\FilterConfigHandler();
self::$handlers['logging.ini'] = new \Mojavi\Config\LoggingConfigHandler();
self::$handlers['modules/*/config/module.ini'] = new \Mojavi\Config\ModuleConfigHandler();
?>