<?php
// auth-generated by DatabaseConfigHandler
// date: 05/05/2015 07:29:38

$database = new \Mojavi\Database\MongoDatabase();
$database->initialize(array('method' => 'dsn', 'dsn' => 'mongodb://localhost', 'database' => 'flux_admin'));
$this->databases['default'] = $database;
$database = new \Mojavi\Database\MongoDatabase();
$database->initialize(array('method' => 'dsn', 'dsn' => 'mongodb://localhost', 'database' => 'flux_admin'));
$this->databases['admin'] = $database;
$database = new \Mojavi\Database\MongoDatabase();
$database->initialize(array('method' => 'dsn', 'dsn' => 'mongodb://localhost', 'database' => 'flux_util'));
$this->databases['util'] = $database;
$database = new \Mojavi\Database\MongoDatabase();
$database->initialize(array('method' => 'dsn', 'dsn' => 'mongodb://localhost', 'database' => 'flux_lead'));
$this->databases['lead'] = $database;
$database = new \Mojavi\Database\MongoDatabase();
$database->initialize(array('method' => 'dsn', 'dsn' => 'mongodb://localhost', 'database' => 'flux_queue'));
$this->databases['queue'] = $database;
?>