<?php
// auth-generated by FilterConfigHandler
// date: 07/06/2015 15:49:26

$filters = array();
$filter = new \Mojavi\Filter\ExecutionTimeFilter();
$filter->initialize($this->context, array('comment' => true));
$filters[] = $filter;
$list[$moduleName] =& $filters;
?>