<?php
// auth-generated by FactoryConfigHandler
// date: 05/05/2015 07:29:38

$this->request = \Mojavi\Request\Request::newInstance('\Mojavi\Request\WebRequest');
$this->storage = \Mojavi\Storage\Storage::newInstance('\Mojavi\Storage\SessionStorage');
$this->user = \Mojavi\User\User::newInstance('\Mojavi\User\BasicSecurityUser');
$this->context = new \Mojavi\Core\Context($this, $this->request, $this->user, $this->storage, $this->databaseManager);
$this->request->initialize($this->context, null);
$this->storage->initialize($this->context, array('session_name' => 'flux'));
$this->user->initialize($this->context, null);

if (MO_USE_SECURITY)
{
	$this->securityFilter = \Mojavi\Filter\SecurityFilter::newInstance('\Mojavi\Filter\BasicSecurityFilter');
	$this->securityFilter->initialize($this->context, null);
}

?>