<?php
// auth-generated by DefineConfigHandler
// date: 07/06/2015 15:49:26
if (!defined('MO_DEFAULT_MODULE')) { define('MO_DEFAULT_MODULE', 'Default'); }
if (!defined('MO_DEFAULT_ACTION')) { define('MO_DEFAULT_ACTION', 'Index'); }
if (!defined('MO_ERROR_404_MODULE')) { define('MO_ERROR_404_MODULE', 'Default'); }
if (!defined('MO_ERROR_404_ACTION')) { define('MO_ERROR_404_ACTION', 'Error404'); }
if (!defined('MO_LOGIN_MODULE')) { define('MO_LOGIN_MODULE', 'Default'); }
if (!defined('MO_LOGIN_ACTION')) { define('MO_LOGIN_ACTION', 'Login'); }
if (!defined('MO_MODULE_DISABLED_MODULE')) { define('MO_MODULE_DISABLED_MODULE', 'Default'); }
if (!defined('MO_MODULE_DISABLED_ACTION')) { define('MO_MODULE_DISABLED_ACTION', 'ModuleDisabled'); }
if (!defined('MO_SECURE_MODULE')) { define('MO_SECURE_MODULE', 'Default'); }
if (!defined('MO_SECURE_ACTION')) { define('MO_SECURE_ACTION', 'Secure'); }
if (!defined('MO_UNAVAILABLE_MODULE')) { define('MO_UNAVAILABLE_MODULE', 'Default'); }
if (!defined('MO_UNAVAILABLE_ACTION')) { define('MO_UNAVAILABLE_ACTION', 'Unavailable'); }
if (!defined('MO_AVAILABLE')) { define('MO_AVAILABLE', true); }
if (!defined('MO_ACTION_ACCESSOR')) { define('MO_ACTION_ACCESSOR', 'action'); }
if (!defined('MO_MODULE_ACCESSOR')) { define('MO_MODULE_ACCESSOR', 'module'); }
if (!defined('MO_CONTENT_TYPE')) { define('MO_CONTENT_TYPE', 'html'); }
if (!defined('MO_MOD_PUB')) { define('MO_MOD_PUB', '/modpub'); }
if (!defined('MO_PATH_INFO_ARRAY')) { define('MO_PATH_INFO_ARRAY', 'SERVER'); }
if (!defined('MO_PATH_INFO_KEY')) { define('MO_PATH_INFO_KEY', 'PATH_INFO'); }
if (!defined('MO_URL_FORMAT')) { define('MO_URL_FORMAT', 'GET'); }
if (!defined('MO_USE_DATABASE')) { define('MO_USE_DATABASE', true); }
if (!defined('MO_USE_SECURITY')) { define('MO_USE_SECURITY', true); }
if (!defined('MO_USER_NAMESPACE')) { define('MO_USER_NAMESPACE', 'org/mojavi'); }
if (!defined('MO_CACHE_USER')) { define('MO_CACHE_USER', 'apache'); }
if (!defined('MO_CACHE_GROUP')) { define('MO_CACHE_GROUP', 'apache'); }
if (!defined('MO_THEME_FOLDER')) { define('MO_THEME_FOLDER', 'default'); }
if (!defined('MO_API_URL')) { define('MO_API_URL', 'http://api.flux.dev'); }
if (!defined('MO_UPLOAD_FOLDER')) { define('MO_UPLOAD_FOLDER', '/home/flux/pub/webapp/meta/uploads'); }
if (!defined('MO_UPLOAD_HOST')) { define('MO_UPLOAD_HOST', 'localhost'); }
if (!defined('MO_UPLOAD_USERNAME')) { define('MO_UPLOAD_USERNAME', 'flux'); }
if (!defined('MO_UPLOAD_PASSWORD')) { define('MO_UPLOAD_PASSWORD', 'm3g@gun'); }
if (!defined('MO_MAIL_HOSTNAME')) { define('MO_MAIL_HOSTNAME', 'ASPMX.L.GOOGLE.com'); }
if (!defined('MO_MAIL_USERNAME')) { define('MO_MAIL_USERNAME', 'hobby.red5@gmail.com'); }
if (!defined('MO_MAIL_PASSWORD')) { define('MO_MAIL_PASSWORD', 'jedin1te'); }
if (!defined('MO_LOG_FOLDER')) { define('MO_LOG_FOLDER', '/var/log/flux'); }
if (!defined('MO_VERSION_FILE')) { define('MO_VERSION_FILE', '/home/flux/pub/webapp/meta/version'); }
if (!defined('MO_USE_APC')) { define('MO_USE_APC', 0); }
if (!defined('MO_PASSWORD_SALT')) { define('MO_PASSWORD_SALT', 'password'); }
if (!defined('MO_DEFAULT_DATETIME_FORMAT_MOMENT_JS')) { define('MO_DEFAULT_DATETIME_FORMAT_MOMENT_JS', 'YYYY-MM-DD HH:mm:ss'); }
if (!defined('MO_DEFAULT_DATE_FORMAT_MOMENT_JS')) { define('MO_DEFAULT_DATE_FORMAT_MOMENT_JS', 'YYYY-MM-DD'); }
if (!defined('MO_DEFAULT_DATETIME_FORMAT_PHP')) { define('MO_DEFAULT_DATETIME_FORMAT_PHP', 'Y-m-d H:i:s'); }
if (!defined('MO_DEFAULT_DATE_FORMAT_PHP')) { define('MO_DEFAULT_DATE_FORMAT_PHP', 'Y-m-d'); }
if (!defined('MO_REALTIME_URL')) { define('MO_REALTIME_URL', 'http://www.fluxfe.dev'); }
if (!defined('MO_PAGE2IMAGES_API')) { define('MO_PAGE2IMAGES_API', '163e945a6c976b6b'); }
if (!defined('MO_ANALYTIC_DOMAIN')) { define('MO_ANALYTIC_DOMAIN', 'localhost'); }
?>