<?php
// auth-generated by FilterConfigHandler
// date: 04/24/2015 05:23:27

$filters = array();
$filter = new \Mojavi\Filter\ExecutionTimeFilter();
$filter->initialize($this->context, array('comment' => true));
$filters[] = $filter;
$list[$moduleName] =& $filters;
?>