<?php
// auth-generated by ModuleConfigHandler
// date: 07/07/2015 10:51:31
define('MOD_REPORT_ENABLED', true);
define('MOD_REPORT_VERSION', 1.0);
define('MOD_REPORT_NAME', 'Report');
define('MOD_REPORT_DESCRIPTION', 'A Report module');
?>