<?php
// auth-generated by ModuleConfigHandler
// date: 04/24/2015 06:47:07
define('MOD_REPORT_ENABLED', true);
define('MOD_REPORT_VERSION', 1.0);
define('MOD_REPORT_NAME', 'Report');
define('MOD_REPORT_DESCRIPTION', 'A Report module');
?>