<?php
// auth-generated by ModuleConfigHandler
// date: 05/05/2015 07:30:30
define('MOD_CAMPAIGN_ENABLED', true);
define('MOD_CAMPAIGN_VERSION', 1.0);
define('MOD_CAMPAIGN_NAME', 'Campaign');
define('MOD_CAMPAIGN_DESCRIPTION', 'A Campaign module');
?>