<?php
// auth-generated by ModuleConfigHandler
// date: 07/06/2015 15:49:40
define('MOD_CAMPAIGN_ENABLED', true);
define('MOD_CAMPAIGN_VERSION', 1.0);
define('MOD_CAMPAIGN_NAME', 'Campaign');
define('MOD_CAMPAIGN_DESCRIPTION', 'A Campaign module');
?>