<?php
// auth-generated by ModuleConfigHandler
// date: 05/05/2015 07:30:23
define('MOD_ACCOUNT_ENABLED', true);
define('MOD_ACCOUNT_VERSION', 1.0);
define('MOD_ACCOUNT_NAME', 'Account');
define('MOD_ACCOUNT_DESCRIPTION', 'A Account module');
?>