<?php
// auth-generated by ModuleConfigHandler
// date: 05/05/2015 12:54:12
define('MOD_REPORT_ENABLED', true);
define('MOD_REPORT_VERSION', 1.0);
define('MOD_REPORT_NAME', 'Report');
define('MOD_REPORT_DESCRIPTION', 'A Report module');
?>