<?php
// auth-generated by ModuleConfigHandler
// date: 07/07/2015 11:47:36
define('MOD_ACCOUNT_ENABLED', true);
define('MOD_ACCOUNT_VERSION', 1.0);
define('MOD_ACCOUNT_NAME', 'Account');
define('MOD_ACCOUNT_DESCRIPTION', 'A Account module');
?>