<?php
// auth-generated by ModuleConfigHandler
// date: 05/05/2015 07:29:38
define('MOD_DEFAULT_ENABLED', true);
define('MOD_DEFAULT_VERSION', 1.0);
define('MOD_DEFAULT_NAME', 'Default');
define('MOD_DEFAULT_DESCRIPTION', 'A Default module');
?>