<?php
// auth-generated by ModuleConfigHandler
// date: 07/06/2015 15:49:26
define('MOD_DEFAULT_ENABLED', true);
define('MOD_DEFAULT_VERSION', 1.0);
define('MOD_DEFAULT_NAME', 'Default');
define('MOD_DEFAULT_DESCRIPTION', 'A Default module');
?>