<?php
// auth-generated by ModuleConfigHandler
// date: 04/24/2015 06:15:15
define('MOD_ACCOUNT_ENABLED', true);
define('MOD_ACCOUNT_VERSION', 1.0);
define('MOD_ACCOUNT_NAME', 'Account');
define('MOD_ACCOUNT_DESCRIPTION', 'A Account module');
?>