<?php
// auth-generated by ModuleConfigHandler
// date: 07/07/2015 11:46:24
define('MOD_CHART_ENABLED', true);
define('MOD_CHART_VERSION', 1.0);
define('MOD_CHART_NAME', 'Chart');
define('MOD_CHART_DESCRIPTION', 'A Chart module');
?>