<?php
// auth-generated by ModuleConfigHandler
// date: 07/06/2015 15:56:23
define('MOD_LEAD_ENABLED', true);
define('MOD_LEAD_VERSION', 1.0);
define('MOD_LEAD_NAME', 'Lead');
define('MOD_LEAD_DESCRIPTION', 'A Lead module');
?>