<?php
// auth-generated by ModuleConfigHandler
// date: 04/24/2015 05:23:27
define('MOD_DEFAULT_ENABLED', true);
define('MOD_DEFAULT_VERSION', 1.0);
define('MOD_DEFAULT_NAME', 'Default');
define('MOD_DEFAULT_DESCRIPTION', 'A Default module');
?>